name: tbr_chatbot
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: 7.8.4
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: 7.3.2
  flutter_gen_runner: 5.4.0
  flutter_lints: ^2.0.0
  freezed: 2.4.7

flutter_gen:
  output: lib/presentation/constants/gen/
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      style: dot-delimiter
      class_name: ProjectAssets

  fonts:
    enabled: true
    outputs:
      class_name: ProjectFontFamily

  colors:
    enabled: false

flutter:
  uses-material-design: true
